### PR TITLE
Default template change proposal

### PR DESCRIPTION
**Pull request by glpzzz**
Referring to `<dl>`: 

>  Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).

as stated in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl.

I propose this change following the example in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_div_elements

Proposed markup is...

```
<div>
    The header if provided
    <dl>
        <div>
            <dt>id</dt>
            <dd>1</dd>
        </div>
        <div>
            <dt>username</dt>
            <dd>tests 1</dd>
        </div>
        <div>
            <dt>status</dt>
            <dd>true</dd>
        </div>
    </dl>
</div>
```

...which I think is more semantic than the combination of `span` and `div` in the current template. 

A preview (with a bit of CSS) can be seen on https://codepen.io/glpzzz/pen/VwNYKwq 

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | Changes the output

### CODE REVIEW

**Comment by terabytesoftw** [comment]
And what happens if I want to use a view, using grid and mansory to display images, will it work?

**Comment by glpzzz** [comment]
Ignore, made it as a test to check why the other (!173) wasn't completing checks.

**Comment by glpzzz** [comment]
> And what happens if I want to use a view, using grid and mansory to display images, will it work?

please, let's discuss in https://github.com/yiisoft/yii-dataview/pull/173

**Comment by glpzzz** [comment]
> And what happens if I want to use a view, using grid and mansory to display images, will it work?

It should as it only a changes the markup elements used to improve semantics, any specific visual appearance can be achieved with CSS.

**Pull request closed without merging**
