### PR TITLE
Default template change proposal

### PR DESCRIPTION
**Pull request by glpzzz**
Referring to `<dl>`: 

>  Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).

as stated in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl.

I propose this change following the example in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#wrapping_name-value_groups_in_div_elements

Proposed markup is...

```
<div>
    The header if provided
    <dl>
        <div>
            <dt>id</dt>
            <dd>1</dd>
        </div>
        <div>
            <dt>username</dt>
            <dd>tests 1</dd>
        </div>
        <div>
            <dt>status</dt>
            <dd>true</dd>
        </div>
    </dl>
</div>
```

...which I think is more semantic than the combination of `span` and `div` in the current template. 

A preview (with a bit of CSS) can be seen on https://codepen.io/glpzzz/pen/VwNYKwq 

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | Changes the output

### CODE REVIEW

**Comment by samdark** [comment]
👍 Good idea. I like the proposal.

**Comment by samdark** [comment]
Can you fix tests to match new markup?

**Comment by glpzzz** [comment]
> Can you fix tests to match new markup?
> 

Yes. Working on it

**Comment by glpzzz** [comment]
Tests update completed. Can I get some help about the current issue? @samdark @vjik

**Comment by samdark** [comment]
Hold on a bit. There's internal discussion aboit the change going on. Need some time.

**Comment by vjik** [comment]
Detail view, by fact, is key-value list. Semantically `dd`/`dt`/`dl` tags is well suited for this case.

`dt` and `dl` tags permit [flow content](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#flow_content). Seems it's cover all cases.

Docs:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dd
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

I like this suggestion.

**Review by samdark — APPROVED** [review]

**Review by Tigrov — APPROVED** [review]

**Review by vjik — APPROVED** [review]

**Pull request merged**
